{{ config(materialized='table') }}

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_TYPE,
    COUNT(DISTINCT f.SALE_LINE_ID) AS TOTAL_ORDERS,
    SUM(f.INV_QTY) AS TOTAL_QTY,
    SUM(f.GROSS_SALES) AS TOTAL_GROSS_SALES,
    SUM(f.NET_AMOUNT) AS TOTAL_NET_AMOUNT,
    SUM(f.DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    AVG(f.DISCOUNT_PERCENT) AS AVG_DISCOUNT_PERCENT,
    MIN(f.INV_DATE) AS FIRST_PURCHASE_DATE,
    MAX(f.INV_DATE) AS LAST_PURCHASE_DATE,
    SUM(CASE WHEN f.LINE_SEVERITY_FLAG = TRUE THEN 1 ELSE 0 END) AS HIGH_SEVERITY_COUNT,
    CURRENT_TIMESTAMP() AS ETL_DATE_CREATED
FROM {{ ref('customer_dim') }} c
LEFT JOIN {{ ref('sales_fact') }} f
    ON c.CUSTOMER_ID = f.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_TYPE
